### ISSUE TITLE
Can't connect! 

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [tympanix/Electorrent#256]
Each time I run the appimage I get:
```sh
Could not establish debug connection Error: Cannot find module 'electron-connect'
Require stack:
- /tmp/.mount_ElectoMiuo1Q/resources/app.asar/app.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at createTorrentWindow (/tmp/.mount_ElectoMiuo1Q/resources/app.asar/app.js:80:26)
    at App.<anonymous> (/tmp/.mount_ElectoMiuo1Q/resources/app.asar/app.js:168:5)
    at App.emit (events.js:315:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/.mount_ElectoMiuo1Q/resources/app.asar/app.js', undefined ]
```

**Comment by EsmailELBoBDev2** [comment]
Okay after looking into it more, it has nothing to do with connecting I guess? so here is issue temp:

**Client:**
- [ ] µTorrent
- [x] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**4.2.5

**Operating System:**Gentoo (btw)

**Application Version:**2.7.3

**Description:** I keep getting the connection could not be established

**Comment by tympanix** [comment]
Hi @EsmailELBoBDev2 

This is actually a npm package used for dev development for live reloading. It is not included in the packaged app and should not be loaded.

I have removed this package since then and expect the issue to be resolved in the next release.

**Comment by EsmailELBoBDev2** [comment]
Well, I already closed my seedbox and do not need to connect to it's torrent client anymore so I think you will find someone else to test it :-p
