### ISSUE TITLE
CI builds fail on a no-op

### ISSUE THREAD

**Issue by reedy** [tympanix/Electorrent#338]
On https://github.com/tympanix/Electorrent/pull/337 which is a no-op, the CI builds fail for various reasons - https://github.com/tympanix/Electorrent/actions/runs/6743622454

**Comment by tympanix** [comment]
Hi @reedy

It seems the CI tests degraded over time without any source code changes. I need to figure out what in the CI environment changed

**Comment by tympanix** [comment]
The acceptance tests regressed because; som docker images used "latest" and broke when new images where published (nginx), electron-builder did not support python3 and python2 was removed for "macos-latest" on Github Actions

**Comment by reedy** [comment]
Still a test failure outstanding...

```
Run xvfb-run -a -- npm test -- -g transmission

> electorrent@2.8.3 test /home/runner/work/Electorrent/Electorrent
> mocha 'test/**/*.spec.ts' "-g" "transmission"



  given transmission service is running (docker-compose)
    given tls/ssl reverse proxy is running (docker-compose)
      given application is running
        1) "before all" hook for "user is logging in with https"


  0 passing (50s)
  1 failing

  1) given transmission service is running (docker-compose)
       given tls/ssl reverse proxy is running (docker-compose)
         given application is running
           "before all" hook for "user is logging in with https":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/Electorrent/Electorrent/test/fixtures/transmission/transmission.spec.ts)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```
